project:
  type: website
  output-dir: docs
  pre-render: _pre-set-updated.py
  preview:
    port: 4321

website:
  title: "DSAN 6000 Slide Hub"
  favicon: "favicon.png"
  repo-url: "https://github.com/jpowerj/dsan6000"
  repo-actions: [source]
  repo-link-target: "_blank"
  sidebar:
    id: mainnav
    title: "DSAN 6000 Slide Hub"
    footer: "*Updated {{< env DSAN6000_LAST_UPDATED \"2024-08-28\" >}}*"
    contents:
      - href: "https://gu-dsan.github.io/6000-fall-2025/"
        text: "<i class='bi bi-arrow-left-short pe-1'></i> Main Course Page"
      - "---"
      - href: w01/index.qmd
        text: "Week 1: Aug 28"
      - href: w02/index.qmd
        text: "Week 2: <span class='sec-w02-date'>Sep 2</span>"
      - href: w03/index.qmd
        text: "Week 3: <span class='sec-w03-date'>Sep 8</span>"
      - href: w04/index.qmd
        text: "Week 4: <span class='sec-w04-date'>Sep 15</span>"
      - href: w05/index.qmd
        text: "Week 5: <span class='sec-w05-date'>Sep 22</span>"
      - href: w06/index.qmd
        text: "Week 6: <span class='sec-w06-date'>Sep 29</span>"
      - href: w07/index.qmd
        text: "Week 7: <span class='sec-w07-date'>Oct 6</span>"
      - href: w08/index.qmd
        text: "Week 8: <span class='sec-w08-date'>Oct 20</span>"
      - href: w09/index.qmd
        text: "Week 9: <span class='sec-w09-date'>Oct 27</span>"
      - href: w10/index.qmd
        text: "Week 10: <span class='sec-w10-date'>Nov 3</span>"
      - href: w11/index.qmd
        text: "Week 11: <span class='sec-w11-date'>Nov 10</span>"
      - href: w12/index.qmd
        text: "Week 12: <span class='sec-w12-date'>Nov 17</span>"
      - href: w13/index.qmd
        text: "Week 13: <span class='sec-w13-date'>Nov 24</span>"
      - href: w14/index.qmd
        text: "Week 14: <span class='sec-w14-date'>Dec 1</span>"
      - href: w15/index.qmd
        text: "Week 15: <span class='sec-w15-date'>Dec 8</span>"
      - "---"
      - href: "https://georgetown.zoom.us/j/91628796534?pwd=BSnBpL4VeysAQMbUtbH4MmwOunglLh.1"
        text: "S<span class='sec-num'>01</span> Zoom Link <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://georgetown.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=9ebe4700-c41f-434a-bb78-b34801332737"
        text: "Recordings <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"
      - href: "https://jjacobs.me/meet"
        text: "Book Office Hour <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 75%;'></i>"
        target: "_blank"

format:
  html:
    theme:
      light: default
      dark: darkly
    css: "/dsan-globals/jjstyles.css"
    toc: true
    link-external-newwindow: true
    link-external-icon: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=='' crossorigin='anonymous' referrerpolicy='no-referrer'></script><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><script src='/sidebar.js'></script>"

