---
title: "DSAN 6000: Big Data and Cloud Computing"
subtitle: "*Fall 2026, Georgetown University*"
sidebar: mainnav
listing:
  sort-ui: false
  filter-ui: false
  type: table
  include:
    categories: "{Class Sessions}"
  fields: [title,date]
  sort: "lecnum asc"
  table-hover: true
  date-format: "MMM D"
format:
  html:
    # link-external-icon: true
    link-external-newwindow: true
---

```{=html}
<style>
.honk-honk {
  font-size: 200% !important;
  /* font-family: "Bungee Spice", sans-serif; */
  font-family: "Honk", sans-serif;
  /* font-optical-sizing: auto; */
  font-weight: 400;
  font-style: normal;
}
.header-table table {
  border: 0px;
}
.header-table > td {
  border-bottom: 0px;
}
</style>
```

::: {.header-table}

```{=html}
<div style="border: 1px solid black; padding-left: 12px; padding-right: 12px; padding-top: 6px; margin-bottom: 10px; border-radius: 20px;">
<center>
<b>Big Data: "When the <i>size</i> of the data itself becomes part of the engineering problem"</b>
</center>
<table>
<thead>
</thead>
<tbody>
<tr>
  <td align="center" rowspan="2" width="15%" style="vertical-align: middle; border-bottom: 0px; border-top: 0px;">Can be <b>processed</b> on single machine?</td>
  <td align="center" width="5%" style="vertical-align: middle; border-right: 2px solid #909090; border-bottom: 0px solid #909090;"><i>No</i></td>
  <td align="center" width="40%" style="vertical-align: middle; border-right: 2px solid #909090; border-top: 2px solid #909090; background-color: #FF991C90;"><span data-qmd="**Medium**<br>(*Parallel Processing*)"></span></td>
  <td align="center" width="40%" style="background-color: #FF991C90; vertical-align: middle; border-top: 2px solid #909090; border-right: 2px solid #909090;"><span data-qmd="[Big!]{.honk-honk}<br>Parallel + Distributed Processing"></span></td>
</tr>
<tr>
  <td align="center" style="vertical-align: middle; border-right: 2px solid #909090; border-bottom: 0px solid #909090;"><i>Yes</i></td>
  <td align="center" style="vertical-align: middle; border-right: 2px solid #909090;"><span data-qmd="Small<br>(*Your Laptop*)"></span></td>
  <td align="center" style="vertical-align: middle; border-right: 2px solid #909090; background-color: #FF991C90;"><span data-qmd="**Medium**<br>(*Data Streaming*)"></span></td>
</tr>
<tr>
  <td style="border-bottom: 0px;"></td>
  <td style="border-bottom: 0px solid #909090;"></td>
  <td align="center" style="vertical-align: middle; border-bottom: 0px solid #909090; padding-bottom: 0px;"><i>Yes</i></td>
  <td align="center" style="vertical-align: middle; border-bottom: 0px solid #909090; padding-bottom: 0px;"><i>No</i></td>
</tr>
<tr>
  <td style="border-bottom: 0px;"></td>
  <td style="border-bottom: 0px;"></td>
  <td align="center" colspan="2" style="border-bottom: 0px; padding-bottom: 0px;">Can be <b>stored</b> on single machine?</td>
</tr>
</tbody>
</table>
</div>
```

:::

::: {.callout-note title="Irregular Lecture Days"}

Please keep in mind the following "special" days, when course meetings will be shifted or skipped due to holidays:

* **Thursday, August 27**: The **first week** of the course will be a **joint meeting** of both sections:
  * Students in the Thursday section (Section 02) should attend in-person, in Walsh 394
  * Students in the Monday section (Section 01) should attend via [this Zoom link](https://georgetown.zoom.us/j/94373215953?pwd=PWr04WbKeGPRAmpNdavBe2cOw9YFFP.1)
* **Tuesday, September 8**: The **Week 3 meeting** for the Monday section (Section 01) falls on a **Tuesday**, as the University follows a Monday schedule on this day (due to the Labor Day holiday on Monday, September 7)
* **Monday, October 12** and **Thursday, October 15**: No class due to Georgetown's Mid-Semester Holiday
* **Monday, November 23** and **Thursday, November 26**: No class due to Georgetown's 2026 Fall Recess

:::

Welcome! This webpage contains slides, resources, and lecture recordings for *DSAN 6000: Big Data and Cloud Computing*, Fall 2026 at Georgetown University.

Section <span class='sec-num'>01</span> of the course takes place on **<span class='sec-day-full'>Wednesday</span>** from **<span class='sec-start'>3:30pm</span> to <span class='sec-end'>6:00pm</span>** in **<span class='sec-room'>Walsh 394</span>**. Use the links in the sidebar, or in the table below, to explore the content for a particular week.

