---
title: "Resource Hub"
sidebar: mainnav
listing:
  id: writeups
  type: grid
  categories: true
  contents: "writeups/**/*.qmd"
  image-height: 0px
  fields: [title, subtitle, categories, date]
bibliography: "_DSAN6000.bib"
csl: "chicago-17-no-url.csl"
nocite: |
  @*
format:
  html:
    df-print: kable
---

## In-Class Demos

* [Week 4 Polars Demo (Colab)](https://colab.research.google.com/drive/1tS3nM7FJAqthDqdeXmqgxiOYMcRrFTZq?usp=sharing)
* [Week 4 DuckDB Demo (Colab)](https://colab.research.google.com/drive/1tPlayCjCJqS4D1TKXwtx93knBZhWxqOy?usp=sharing)
* Week 6 Hadoop Demo (Deepnote): [Map-Reduced Matrix-Vector Multiplication](https://deepnote.com/workspace/Columbia-University-f2637961-0c74-4aff-8153-d766baa193ed/project/MapReduceDemo-41367b13-4253-47c8-8ffe-0544456d6070/notebook/DSAN5500HW5-8b90a6af23d34d239b7da0111228614d?utm_source=share-modal&utm_medium=product-shared-content&utm_campaign=notebook&utm_content=41367b13-4253-47c8-8ffe-0544456d6070)
* Week 6 Hadoop &rarr; PySpark Demo (Deepnote): [Tennis Analytics with Hadoop and PySpark RDDs](https://deepnote.com/workspace/dsan-f2637961-0c74-4aff-8153-d766baa193ed/project/PySpark-Demo-5b6d12ee-5b84-4b9c-b217-57081420a97d/notebook/PySparkTennis-e728d4f3669d412fa2af10e6f30b9689?utm_source=share-modal&utm_medium=product-shared-content&utm_campaign=notebook&utm_content=5b6d12ee-5b84-4b9c-b217-57081420a97d)
<!-- * [Week 7 M&M Counts Starter Code (Databricks Free Edition)](https://dbc-7c96f2b7-b70a.cloud.databricks.com/editor/notebooks/1614884783289922?o=3732734799398494) -->
* [Week 7 PySpark DataFrames Demo (Colab)](https://colab.research.google.com/drive/17xglntdFVtGpgJRt_Y3fDELYt4Lycf96?usp=sharing)
  * (Adapted from [Jacob Celestine's PySpark on Colab demo](https://jacobcelestine.com/knowledge_repo/colab_and_pyspark/))
* [Week 8 SparkNLP Demo](https://classroom.github.com/a/f4T20SVq)

## Lab .zips

Access the [ZIP files here](https://jpj.georgetown.domains/dsan6000-zips/)

## Extra Writeups

::: {#writeups}
:::

## Key Books By Week

### Week 1: Course Overview and Week 2: Cloud Computing

* **The Boar Book**: @kleppmann_designing_2017, *Designing Data-Intensive Applications*

### Week 3: Parallel Concepts

* **The Wolohan MapReduce Book**: @wolohan_mastering_2020, *Mastering Large Datasets with Python*, Chapters 1-6

### Week 4: DuckDB, Polars, File Formats

* **The Lynx Book**: @janssens_python_2025, *Python Polars: The Definitive Guide*
* **The I-Need-Ham, Hunger Book**: @needham_duckdb_2024, *DuckDB in Action*

### Week 5: Data Warehousing

Two Packt Books:

* **General Data Engineering on AWS**: @eagar_data_2021, *Data Engineering with AWS*
* **Data Engineering with Athena**: @virtuoso_serverless_2021, *Serverless Analytics with Amazon Athena*

### Weeks 6 and 7: Hadoop &rarr; PySpark

* * **The Wolohan MapReduce Book**: @wolohan_mastering_2020, *Mastering Large Datasets with Python*, Chapters 7-10

### Weeks 8 and 9: Spark in Depth

* **The Electric Eel Book**: @damji_learning_2020, *Learning Spark*

## PDFs of Books

The remainder of this page is auto-generated from all of the references across the slides for each week: click on the **name** of a reference to download the ebook version, if available!

::: {#refs}
:::

