---
title: "Week 5: From DuckDB to Polars"
subtitle: "{{< var course.slides-subtitle >}}"
author: "{{< var course.author >}}"
institute: "{{< var course.institute >}}"
date: 2026-09-28
date-format: full
lecnum: 5
categories:
  - "Class Sessions"
crossref:
  fig-title: Fig
cache: false
bibliography: "../_DSAN6000.bib"
csl: "../chicago-17-no-url.csl"
format:
  revealjs:
    output-file: "slides.html"
    html-math-method: mathjax
    slide-number: true
    scrollable: true
    link-external-icon: true
    link-external-newwindow: true
    footer: "{{< var weeks.5.footer >}}"
    include-in-header:
      text: |
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'>
        <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'>
    theme:
      - default
      - "../dsan-globals/jjquarto.scss"
      - "../dsan-globals/jjquarto-light.scss"
    revealjs-plugins:
      - simplemenu
    simplemenu:
      flat: true
      scale: 0.5
      barhtml:
        header: >
          <div class='menubar'>
            <span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span>
            <span style='position: absolute; right: 0; padding-right: 8px; padding-top: 3px; z-index: 10; display: inline-flex !important; align-items: center !important;'>
              <a id='toggle-01-label' href='#' onclick="window.toggleSectionClicked('01'); return(false);" class='no-decoration'>01</a>
              <a href='#' onclick="window.toggleIconClicked(); return(false);" class='no-decoration'><i id='section-toggle-icon' class='bi bi-toggle-off' style='padding-top: 0px; padding-left: 3px; padding-right: 3px;'></i></a>
              <a id='toggle-02-label' href='#' onclick="window.toggleSectionClicked('02'); return(false);" class='no-decoration'>02</a>
            </span>
            <ul class='menu'></ul>
          </div>
  html:
    output-file: "index.html"
    html-math-method: mathjax
    df-print: kable
---

::: {.content-visible unless-format="revealjs"}

<center class='mb-3'>
<a class="h2" href="./slides.html" target="_blank">Open slides in new tab &rarr;</a>
</center>

:::

# DuckDB &rarr; Polars Roadmap

## HW5: No More Shoving SQL in Python with `"""` {.smaller .crunch-title .title-10}

* **DuckDB:** "Artificial" separation of computation and data
  * HW4 Q3 **Data** loaded into Pandas `DataFrame`
  * HW4 Q3 **Computation** written as SQL expression:
    ``` {.python}
    query = """
    <SQL code>
    """
    ```
  * ...Then you shoved them together: `result_df = con.execute(query).df()`
* **Polars:** "Natural" computation-data separation **within the same language (Python)**
  * HW5 Q2 **Data** loaded into **Polars** `DataFrame` (Python object)
  * HW5 Q2 **Computation** written as **Polars** functions (Python code)
  * `polars` library specifies which functions "activate" **eager evaluation**

# A Less-Rushed Introduction to DuckDB {data-stack-name="DuckDB"}

## DuckDB: Buzzwords $\leadsto$ Understanding {.smaller .crunch-title .title-11 .crunch-p}

> *DuckDB is an **in-process SQL OLAP DBMS**.* [@aubury_getting_2024]

* **Database Management System (DBMS):** An interface between the database and its users, allowing create, read, update, and delete (CRUD) operations on the DB

* **Online Analytical Processing (OLAP):** A **data processing paradigm** focused on applying column-wise aggregation functions and joining large datasets together
  
  *(Contrasts with Online Transaction Processing (OLTP), where frequent writing of individual records (rows) is the dominant pattern of data interaction)*
* **Structured Query Language (SQL):** A *declarative* **programming language** used to store, manipulate, and query records in relational databases – DBs representing data as tables of rows and columns, with formal relationships defined across tables
* **In-process:** DuckDB *embeds within* a process + its memory. Most DBMSs run separately (e.g., on a remote server); DuckDB eliminates **connect/authenticate** steps

## DuckDB as *Ephemeral* DB-In-RAM {.crunch-title .smaller}

* Standalone operation (as its own process, independent of Python): [**DuckDB CLI**](https://shell.duckdb.org/#queries=v0,SELECT-'jeff'-AS-name%2C-3-AS-fav_number~)
* Python operation: Upon **`import duckdb`**, creates a **default, in-memory DB**
  ``` {.python}
  default_mem_con = duckdb.connect(database=':default:')
  ```
  
  <div class='text-70' style='margin-top: 8px; line-height: 1.2;'>*Typically **not** used, if only bc less clear **where** and **when** the DB was created (readers of your code would need to know this fact about `import duckdb`)*</div>
* Setting up a connection creates a **new**, `con`-specific in-memory DB:
  ``` {.python}
  con = duckdb.connect(database=':memory:')
  con = duckdb.connect() # database=':memory:' is default setting
  ```
* Can persist to **file** on disk:
  ``` {.python}
  con = duckdb.connect('my_cool_data.duckdb')
  ```
* **Please note <i class='bi bi-exclamation-triangle'></i>** `duckdb.connect()` is **not** how we connect to the on-disk **data files**, external **S3 objects**, or in-memory **`DataFrame`s** that we want to **run queries on!**
  ``` {.python}
  con.execute('SELECT * FROM my_df LIMIT 5;')
  ```

## SQLite: "DuckDB for OLTP" {.crunch-title}

* Both are simplified in-process DBMSs that connect to a single local file (also both free and open source)
* [SQLite](https://sqlite.org/fiddle/) optimized for **row-oriented**, **OLTP** workloads
* DuckDB optimized for **column-oriented**, **OLAP** workloads
* HW6 will give you exposure to **both!**
  * <i class='bi bi-1-circle'></i> SQLite for OLTP ingestion of events
  * <i class='bi bi-2-circle'></i> **Athena** (coming soon) for "automatic" ETL
  * <i class='bi bi-3-circle'></i> DuckDB for OLAP inference (MLFlow)

# A Non-Sprinted Introduction to Polars {data-stack-name="Polars"}

## Polars (in Jeff's Mental Model) {.crunch-p .crunch-title .crunch-li-10}

* **Polars** = Tool written in **Rust** for fast (query-optimized), distributed, `DataFrame`-esque OLAP workflows
* `polars` = **Python** library for "high-level" (Python-level) interaction with **Polars**
* If we want **optimized**, **distributed** processing, we need **lazy execution** (enabling logical $\leadsto$ physical query plan)...
* Query optimization via lazy execution **not part of `pandas`!**
* $\implies$ Let's find a lazy-execution-focused library that "feels" as close to Pandas as possible... that's `polars`!

## Lab Time!

<center>

[Week 5 Lab: Polars](https://colab.research.google.com/drive/1Ma8uX8ISiYrlaDVTGztciZNTRRR3KG0E?usp=drive_link){.boxed-cb}

</center>

## References

::: {#refs}
:::
