## DuckDB: A Quick Introduction

[DuckDB](https://duckdb.org/): an in-process SQL OLAP DB management system

``` {.bash code-line-numbers="false"}
pip install duckdb
```

---

2. [Modern Data Stack in a Box with DuckDB](https://duckdb.org/2022/10/12/modern-data-stack-in-a-box.html): DuckDB, Meltano, Dbt, Apache Superset

---

## DuckDB and Apache Arrow for NYC Taxi Dataset

This notebook reads the NYC taxi dataset files for the year 2021 (about 29m rows) and runs some analytics operation on this dataset. This dataset is **too big to fit in memory** 

1. We read the data from S3 using apache Arrow (pyarrow).

2. The zero-copy integration between DuckDB and Apache Arrow allows for rapid analysis of larger than memory datasets in Python and R using either SQL or relational APIs.

3. We create a DuckDB instance in memory and using the connection to this in-memory database We run some simple analytics operations using SQL syntax.

Also see [https://duckdb.org/2021/12/03/duck-arrow.html](https://duckdb.org/2021/12/03/duck-arrow.html)